"
""ejecutando esto se agrega el file a la libreria de Cuoora""
""CuooraFileLibrary addFileAt: 'C:\pharo\main.css'.""


"
Class {
	#name : #CuooraFileLibrary,
	#superclass : #WAFileLibrary,
	#category : #'Objetos_2-Cuoora-UI'
}

{ #category : #uploaded }
CuooraFileLibrary >> mainCss [
	^ '.right {
  float: right;
}
a {
  text-decoration: none;
  color: rgb(0,15,70);
}
body {
  font-family: Lucida Sans Unicode, Lucida Grande, sans-serif;
}'
]
